# conf/data_structure/base.yaml

#主要是有关数据处理的,影响结果的参数与文件结构描述
primary_dataset: "default_dataset"

filenames:
  raw:
    authoritative_dti: "default_interactions.csv"
    raw_tsv: "default_raw.tsv"
    dummy_file_to_get_dir: "dummy.txt"
    interactions: "interactions_default.csv"
    ligands: "ligands_default.csv"
  processed:
    common:
      nodes_metadata: "nodes.csv"
      node_features: "node_features.npy"
      feature_caches:
        molecule_embeddings: "feature_caches/molecule_features.pkl"
        protein_embeddings: "feature_caches/esm_protein_features.pkl"
      similarity_matrices:
        molecule: "sim_matrixes/dl_similarity_matrix.pkl"
        protein: "sim_matrixes/prot_similarity_matrix.pkl"
    specific:
      graph_template: "{prefix}_graph_{suffix}.csv"
      labels_template: "{prefix}_labels_{suffix}.csv"
  cache:
    feature_template: "{entity_type}/{model_name}/{authoritative_id}.pt"
paths:
  raw:
    authoritative_dti: "${path:raw.authoritative_dti}"
    raw_tsv: "${path:raw.raw_tsv}"
    dummy_file_to_get_dir: "${path:raw.dummy_file_to_get_dir}"
    interactions: "${path:raw.interactions}"
    ligands: "${path:raw.ligands}"

  processed:
    common:
      nodes_metadata: "${path:processed.common.nodes_metadata}"
      node_features: "${path:processed.common.node_features}"
      feature_caches:
        molecule_embeddings: "${path:processed.common.feature_caches.molecule_embeddings}"
        protein_embeddings: "${path:processed.common.feature_caches.protein_embeddings}"
      similarity_matrices:
        molecule: "${path:processed.common.similarity_matrices.molecule}"
        protein: "${path:processed.common.similarity_matrices.protein}"

    specific:
      graph_template: "${path:processed.specific.graph_template}"
      labels_template: "${path:processed.specific.labels_template}"
  cache:
    feature_template: "${path:cache.feature_template}"
schema:
  internal:
    # 1. 项目内部的、黄金标准的数据格式定义
    authoritative_dti:
      molecule_id: "PubChem_CID"
      protein_id: "UniProt_ID"
      molecule_sequence: "SMILES"
      protein_sequence: "Sequence"
      label: "Label"

    # 2. 图和标签文件的输出格式定义
    graph_output:
      source_node: "source"
      target_node: "target"
      edge_type: "edge_type"

    labeled_edges_output:
      source_node: "source"
      target_node: "target"
      label: "label"

  # 3. 各个原始数据源的列名定义
  #    将它们嵌套在各自的键下，保持结构清晰
  external: {}

runtime:
  variant_folder: "baseline" # 默认值
  experiment_folder: "default-experiment" # 默认值
